StrongMind/canvas-lms

Gemfile.d/development.rb
config/outgoing_mail.yml
lib/host_url.rb

The right change has been made to docker/master example as well

PLAY-41 email with aws/ses. 

---

app/views/shared/_canvas_footer.erb

Pull request reviewed and approved by @captainhurst

Remove Instructure from footer

---

app/coffeescripts/SubmissionDetailsDialog.js
app/stylesheets/components/_forms.scss
app/stylesheets/vendor/bootstrap/_forms.scss
app/views/jst/SubmissionDetailsDialog.handlebars
app/views/jst/_grading_box.handlebars

Teacher can now easily exempt a student from a gradebook item using checkbox on gradebook dialogue.

PLAY 289: Student exempt grade

---

app/stylesheets/base/_ic_app_header.scss

Side bar logo was missing a height and was not displaying as a result. 
Height CSS has been added.

Added height css on logo

---

app/views/layouts/application.html.erb

JIRA Issue collector

---

lib/tasks/strongmind.rake

Turn on analytics in prep for student dashboard.

Turn on analytics

---

app/coffeescripts/gradebook/Gradebook.coffee

Based on Instructure's Canvas gradebook fix:
https://github.com/instructure/canvas-lms/commit/d57fea1186ecada8b70ca71163b1f1a509eb91e8#diff-25f210b23fb4e660232570400d51a3a4

Play 886 fix gradebook

---

public/javascripts/account_settings.js

[PLAY-1080](https://strongmind.atlassian.net/browse/PLAY-1080)
- Added filetype restrictions for uploads

[PLAY-1080] Filetype restrictions for uploads

---

lib/tasks/strongmind_defaults.rake
public/javascripts/course.js
public/javascripts/instructure.js

[PLAY-1183](https://strongmind.atlassian.net/browse/PLAY-1183)
- Added course navigation click listener to trigger GA event

[PLAY-1183] Add Google analytics events for snapshot

---

app/jsx/assignments/StudentExemptions.js

Adds a message beneath the bulk excuse component about the cache-imposed time delay on the excuse tag appearing on the modules page for students.

Play 1263 bulk excuse message

---

app/models/enrollment/recent_activity.rb

This reverts commit 7cd8abe8e4e1ae2574e3e9abc723b659b8228098.

Revert "Revert "privacy is dead""

---

lib/authentication_methods.rb

Added quick and dirty check to redirect migrated users if they happen to login to Clown after their instance handoff date.

Added redirect for migrated cloud users

---

Gemfile.d/_before.rb
Gemfile.d/datadog.rb
app/controllers/submissions_controller.rb
app/views/gradebooks/grade_summary.html.erb
app/views/submissions/show.html.erb
public/javascripts/submissions.js

modified rubric button to take you to the assignment.

STK-934: Behavioral: modified rubric button to take you to the assignment.

---

Gemfile.d/datadog.rb

Devops-2411 PR request Redux. Now submitted to the proper repo. Strongmind/canvas-lms

removing datadog.rb gemfile from Gemfile.d

---

app/controllers/users_controller.rb
config/initializers/sentry.rb

…red by sentry."
This reverts commit 3809aa0be280e096c83ec43268ba3661e23fe18c.

QTY-474: revert commit

---

config/initializers/active_record.rb

lookout - gigantic code change ahead

QTY-347 submission/grading retries fix

---

app/models/context_module_progression.rb

Co-authored-by: Angel Diaz <angel.diaz@strongmind.com>

QTY-362 truncate source in delayed_jobs

---

app/models/context_module_progression.rb

Co-authored-by: Angel Diaz <angel.diaz@strongmind.com>
Co-authored-by: Charles Parisi <charles.parisi@strongmind.com>

QTY-362 truncate source in delayed jobs before save if length exceeds limit

---

app/models/quizzes/quiz.rb

QTY-378 return if user is nil when checking if quiz is locked

---

app/coffeescripts/views/conferences/EditConferenceView.coffee
app/stylesheets/bundles/conferences.scss
app/views/jst/conferences/editConferenceForm.handlebars

[QTY-1080](https://strongmind.atlassian.net/browse/QTY-1080)
Implementing a search bar underneath the filtering for users in the conference edit form.
Written in javascript to work with the existing filtering implementation
Tested locally with different test cases.

QTY-1080 Implement search bar filtering for users in conference creation

---

Gemfile.d/_before.rb
app/assets/javascripts/application.js
config/initializers/shim_settings_service.rb

[QTY-1300](https://strongmind.atlassian.net/browse/QTY-1300)
Removes the need to apply the shim patch to get canvas running locally
Applies the changes the shim does dynamically based on environment
Integration testing, tested common functionality and JQuery

QTY-1300 Remove the need to apply shim patch

---

app/models/assignment/speed_grader.rb
lib/gradebook_exporter.rb
lib/gradebook_settings_helpers.rb

QTY-1497: fix issue with gradebook not exporting.

---

app/models/assignment/speed_grader.rb

QTY-1497: fix call to gradebook_enrollment_scope

---

lib/gradebook_exporter.rb

QTY-1497: remove preload when setting enrollment_scope

---

app/models/assignment_group.rb
app/models/content_migration.rb
app/models/context_module.rb
app/models/importers/context_module_importer.rb

[QTY-1355](https://strongmind.atlassian.net/browse/QTY-1355)
Allow school personnel to set a school wide default minimum threshold at the account level that is reflected on all new and currently created (but not yet started) courses by assignment group. 
Update account settings page to have fields for a pre-determined set of assignment groups, replacing the existing threshold fields for assignments and exams. 
Adds `AssignmentGroup::GROUP_NAMES` constant to hold the assignment groups for which we will support adding default thresholds. 
Utilizes the existing `RequirementsService` and `SettingsService` to dynamically get and set thresholds for the supported assignment groups. 
Adds callbacks to `assignment_decorator.rb` and `content_migration_decorator.rb` as well as delayed jobs in …

QTY-1355: Add assignment group passing thresholds to account settings

---

lib/messageable_user/calculator.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-4048)
Solve an exception coming through trying to access roles
Add left join to query on roles so the method has access to a users role
Deployed to new_id_sandbox

QTY-4048: Add left join on roles to solve exception

---

package.json
yarn.lock

Reverts StrongMind/canvas-lms#529

Revert "Bump tinymce from 4.5.7 to 5.10.8"

---

package.json
yarn.lock

Reverts StrongMind/canvas-lms#532

Revert "Bump lodash from 4.17.4 to 4.17.21"

---

config/initializers/sentry.rb

Passed a proposal to do this during the logging discussion with leads.
https://docs.sentry.io/platforms/ruby/configuration/options/#tracing-options

Sample sentry transactions

---

package.json
yarn.lock

Reverts StrongMind/canvas-lms#543

Revert "Bump tinymce from 4.5.7 to 5.10.9"

---

package.json
yarn.lock

Reverts StrongMind/canvas-lms#542

Revert "Bump axios from 0.21.2 to 1.6.0"

---

gems/canvas_i18nliner/package.json
gems/canvas_i18nliner/yarn.lock

Reverts StrongMind/canvas-lms#547

Revert "Bump handlebars from 1.3.0 to 4.7.7 in /gems/canvas_i18nliner"

---

app/controllers/application_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/HWTJ-2)
Save launchdarkly queries and performance issues that will result.
Use rails caching API
Will test on new-id-sandbox

Cache feature flag call

---

app/messages/assignment_created.email.erb
app/messages/assignment_created.email.html.erb
app/messages/assignment_created.sms.erb
app/messages/assignment_created.summary.erb
app/messages/assignment_created.twitter.erb

[QTY-6231](https://strongmind.atlassian.net/jira/software/c/projects/QTY/boards/575?selectedIssue=QTY-6231)
To fix sentry [issue](https://strongmind-4j.sentry.io/issues/4916400007/events/85f87256d32d4af4b296aa1369e64326/?project=6262567&referrer=next-event) undefined method `[]' for nil:NilClass
Check nils in partial and display "N/a" if no due date on assignment
n/a
[QTY-6231]: https://strongmind.atlassian.net/browse/QTY-6231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-6231: catch due_at nils in partial

---

app/views/layouts/application.html.erb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/FSTN-599)
Send my Y axis position to the inner iframe
Post a message to the inner frame and send over my position
NA
NA

FSTN-599: Post a message to the inner iframe

---

app/views/layouts/application.html.erb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/FSTN-599)
I want to know the inner height of the iframe
Send the inner in a message

FSTN-599: Post message containing the inner height

---

app/models/enrollment/recent_activity.rb

Reverts StrongMind/canvas-lms#597

Revert "QTY-6959: Try addressing long-standing deadlocks"

---

app/views/jst/courses/roster/rosterUser.handlebars

Reverts StrongMind/canvas-lms#598

Revert "KAPE-5194: Hide old custom placement button"

---

config/initializers/sentry.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-13623)
Sample calls to grade passback to find performance issues
Update Sentry initializer to check for url and turn on sampling when appropriate

Enable Sentry TPM for Grade Passback

---

.github/workflows/submodule_update.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-11338)
Authorize action to use GH
Added a new token probably b/c old token was expired
Merge run and verify

QTY-11338 Add a new token

---

.github/workflows/submodule_update.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-11338)
Address action run failure, `Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
Error: The process '/usr/bin/git' failed with exit code 128`
update action to v4, remove token from action b/c don't believe this is needed
Merge run and verify

QTY-11338 Update checkout action to v4

---

config/initializers/rack_timeout.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-5273)
To link canvas telemetry to Learnosity player.
Modified the slow query logic to include sentry trace for better observability using the SentryHub in the thread.
Local Testing

SlowQuery Upgrade

---

app/controllers/assignment_groups_controller.rb
lib/api/v1/assignment_group.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-14666)
Wrong syntax for preloader
Use correct Active Record syntax

(S) QTY-14666: Fix syntax for preloader

---

lib/gradebook_importer.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-17617)
Fix the "Couldn't find header row" error that is occurring in production when importing gradebooks. This error happens when the CSV contains malformed or truncated rows, which would cause the importer to crash and trigger Sentry alerts.
Added several layers of error handling to make the gradebook importer more robust:
1. Enhanced header row detection with better error checking
2. Added error handling to CSV parsing to prevent crashes on malformed data
3. Included more detailed error logging for easier debugging
4. Added safeguards against index out of bounds errors
5. Added a check to verify that a valid header was found during import
1. Upload a properly formatted gradebook CSV file - should import correctly
2. …

QTY-17617 Fix Gradebook Importer header row error
