StrongMind/canvas-lms

app/views/shared/_canvas_footer.erb

Removed logo and renamed to "Modified Open Source" per previous discussions.
[VIEW LICENSE](https://github.com/instructure/canvas-lms/blob/stable/LICENSE#L196)
>>> New and old look

remove instructure logo from dashboard

---

app/stylesheets/base/_layout.scss

body.full-width.grades <=== targets BOTH gradebook and speedgrader
body.full-width.grades:not(.gradebook) <=== targets ONLY speedgrader, so that speedgrader ignores the left side bar.

CSS now targets speed grader specifically, rather than both grades pages

---

app/coffeescripts/models/Message.coffee
app/coffeescripts/views/conversations/MessageDetailView.coffee
app/controllers/conversations_controller.rb
app/models/role_override.rb
app/views/jst/conversations/messageDetail.handlebars
app/views/jst/conversations/messageItem.handlebars

[PLAY-1007](https://strongmind.atlassian.net/browse/PLAY-1007)
[Related PR #105](https://github.com/StrongMind/canvas_shim/pull/105)
- Added `CAN_DELETE_INBOX_MESSAGES` to js env to make available to inbox views
- Added check for permission for all views that include delete button in inbox

Play 1007 add permission for delete inbox

---

app/controllers/users_controller.rb
config/initializers/sentry.rb

Having sentry ignore this exception: This is to cut down on "exceptions" occurring that are actually normal application behavior. The HTTPS response from the server alerts the server of a 400 response already. Raising an exception as well is overly verbose and leads to alert fatigue/misinformation.

QTY-474 Sentry Ignore ActiveRecord::RecordInvalid

---

app/controllers/conferences_controller.rb
app/models/big_blue_button_conference.rb
spec/controllers/conferences_controller_spec.rb
spec/fixtures/files/conferences/big_blue_button_get_recordings_bulk.json
spec/models/big_blue_button_conference_spec.rb

[QTY-1034](https://strongmind.atlassian.net/browse/QTY-1034)
Increase performance of slow loading in Conferences page
Use the same API method with multiple meeting ids to load all the recordings up in one go instead of making a bunch of individual calls
We created about 250-500 conferences locally and in newidsandbox and measured performance before and after our fix. We also deployed to poes to test a real worst case scenario. Performance in poes went from 1.4 minutes to 11 seconds.
Passing methods to as_json executes the methods and includes the result and calling that method individually for each conference was the cause of poor performance.
(cherry picked from commit 82acf24eaac2d66fc79cc519c885329be40665c3)

QTY-1034: preload big blue button conference recording data

---

Gemfile.d/app.rb

This reverts commit 5ae658895e721a2018fc3d5b87f9d40c3c664a52.

Revert "QTY-1136 added sentry delayed job gem"

---

lib/feature.rb

[QTY-1199](https://strongmind.atlassian.net/browse/QTY-1199)
Teachers would like the ability to schedule recurring calendar events (calendar duplicates) so that they don’t have to create them each manually.
We found that this feature already exists but is behind canvas’s feature flag system, however the flag was in beta, had opt-in required, and had a “hidden” status. We found that one teacher was unable to view the feature even if turned on. To make this visible for all users, we’ve set the following on the feature flag:
- don’t require opt-in
- set state to “allowed”
- set beta status to "false"
We deployed our change to the sandbox environment and verified that all user roles can use the recurring calendar events feature.
Before changes:
After changes:

QTY-1199 recurring calendar events feature flag adjustment

---

Gemfile
Gemfile.d/_before.rb
Gemfile.d/app.rb
config/application.rb
lib/canvas_yaml.rb

[QTY-991](https://strongmind.atlassian.net/browse/QTY-991?atlOrigin=eyJpIjoiOTJmYWY1YWQ2MjlhNGY1MGFlMDdkMjAyNTU4NzNmZWMiLCJwIjoiaiJ9)
Upgrade ruby from 2.4.10 to 2.5  for canvas-lms
ultimate goal here is to upgrade to the latest ruby version, doing so incrementally
Built and tested locally

QTY-991: Upgrade to ruby 2.5.0

---

app/controllers/users_controller.rb
app/models/pseudonym.rb

[QTY-418](https://strongmind.atlassian.net/browse/QTY-814)
We get ActiveRecord::RecordNotUnique when posting updates on users. This post leads to an update on Pseudonyms which has an index on it that makes integration_id a unique constraint (it tries to create a duplicate key in that index).
We added the integration_id as a unique constraint on the Pseudonym model so that it becomes a part of validation. When we run into this error, it will get rescued and notify us with a 409 Conflict error status.
We created a user through postman and then tried to create another user with the same integration_id. We tested this locally and in newidsandbox.
Note we have a detailed error: integration_id is taken

QTY-814 add unique constraint on integration_id for Pseudonym

---

Gemfile

[QTY-1413](https://strongmind.atlassian.net/browse/QTY-1413)
#Delete comments under headings and replace with appropriate descriptions for each category
downgrade ruby from 2.6.10 to 2.5, there were more incompatibilities found on thursday with ruby 2.6.
downrade using deps and gemfile
We rolled out this image thursday night.

QTY-1414: downgrade ruby from 2.6.10 to 2.5

---

Gemfile.d/app.rb
Procfile.dev
config/application.rb
config/initializers/launch_darkly.rb
config/puma.rb
config/security.yml
procfile

[QTY-1410](https://strongmind.atlassian.net/browse/QTY-1410)
create a local dev env that supports no docker
create a docker compose file for local, which only runs support services. Foreman is used to start/stop the web & worker
tested on two separate machines

QTY-1410: create local dev env without docker

---

app/models/pseudonym.rb
package.json
yarn.lock

[QTY-1583](https://strongmind.atlassian.net/browse/QTY-1583)
We added a uniqueness check to the integration id a few weeks ago, this introduced a problem when trying to create a new pseudonym with nil values for integration ids. it meant that only one pseudonym could exist with nil for the integration id.
i've moved the validation to the canvas shim where i think it should've been placed initially.
added a spec to test whether or not a Pseudonym is valid when integration is nil. also ran locally to verify that i can now create new users from the users ui in canvas. (previously wasn't working)

QTY-1583: moved integration_id validation to canvas shim

---

app/models/pseudonym.rb

Co-authored-by: Alexandra Davis <alexandra.davis@strongmind.com>
[QTY-814](https://strongmind.atlassian.net/browse/QTY-814)
We are getting ActiveRecord::RecordNotUnique errors on creation of User/Pseudonym because of an index that uses unique_id as a key.
We updated the validation for unique_id to match what is currently in instructure's code.
We tested this in new-id-sandbox by creating a user in rails console and then tried to create the same user with the same unique_id and we were able to see our error ("ID already in use for this account and authentication provider").

QTY-814 update validation on unique_id for Pseudonym creation

---

app/models/assignment_group.rb
public/javascripts/context_modules.js

[QTY-1599](https://strongmind.atlassian.net/browse/QTY-1599)
Allow school personnel to set passing thresholds at the course-level, which take precedence over the account-level passing thresholds (added by [this PR](https://github.com/StrongMind/canvas_shim/pull/412)), if set. 
Update course settings page to have fields for a pre-determined set of assignment groups, replacing the existing threshold fields for assignments and exams.
Utilize AssignmentGroup::GROUP_NAMES constant added by the previous PR to determine which assignment groups we will support passing thresholds for by default.
Utilizes the existing RequirementsService and SettingsService to dynamically get and set thresholds for the supported assignment groups.
Updates the checks in `context_modules_controller_decorator.rb` to …

QTY-1599: Add Threshold settings for all assignment groups at the course level

---

app/controllers/discussion_topics_api_controller.rb
app/models/discussion_topic/materialized_view.rb

[QTY-1504](https://strongmind.atlassian.net/browse/QTY-1504)
Discussion topics have an optional setting that prevents students from viewing posts until they have contributed to the thread. Before this change, students were bypassing this by posting garbage values as a post, viewing other student's posts, and cheating off of their peers. To prevent cheating, we've updated this setting to not only require students to contribute, but to receive a grade for their post, before they can view their peer's contributions (this sits behind a launch darkly flag).
We extended the **materialized_view.rb** by adding a decorator **materialized_view_decorator.rb** which will prevent posts from rendering unless the student viewing the discussion topic has posted and that post has been graded. These checks …

QTY-1504 prevent cheating for graded discussion topics when user must post before viewing all posts

---

config/initializers/shim_settings_service.rb

[QTY-2067](https://strongmind.atlassian.net/browse/QTY-2067)
When working in our development environment, we are receiving errors regarding making calls to the pipeline service. As we typically don't utilize the pipeline service in our dev environment, turning off the setting will alleviate this issue.
The logic was already partially implemented throughout Canvas. We just needed to complete it by changing the setting and utilize Rails cache to make the calls vs. calling the db.
Create a course while watching your logs, the error should no longer appear. In addition, tested on newidsandbox and it is still working as expected.
[QTY-2067]: https://strongmind.atlassian.net/browse/QTY-2067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QTY-2067: Remove pipeline service calls when in development

---

app/controllers/submissions_api_controller.rb

[QTY-2256](https://strongmind.atlassian.net/browse/QTY-2256)
@StrongMind/horseshoes were receiving an abundance of 500 errors as a result of hitting an endpoint in Enterprise Canvas. When making a request to `/courses/:course_id/students/submissions?...`, the resource was returning a 500 error for courses that did not have any assignments with `workflow_state: 'published'`. The purpose of this change is to provide a more appropriate response to these API requests rather simply breaking down. 
Added a check within the method to ensure that assignments are present. If assignments are not present, we return early and render json with an empty array (as is the case when they make an API call to a similar `Assignment` endpoint) and return a `200`, since the resource was found but no records …

QTY-2256: Return empty array when no submissions will exist

---

app/models/pseudonym.rb

[QTY-2601](https://strongmind.atlassian.net/browse/QTY-2601)
In Enterprise Canvas, we were seeing an exception that was preventing users from being able to update login information (login ID, SIS ID, integration ID) from the UI. The application was preventing update due to a failing uniqueness validation. 
A previous [PR](https://github.com/StrongMind/canvas-lms/pull/493) updated a check for uniqueness of the integration ID due to another exception being raised in Sentry. The previous PR used the current Instructure query to fix the issue, however, a key piece of the query was missed during the implementation. 
In the previous fix, we moved away from looking from the `first` active `Pseudonym` record for a `unique_id` for a user:
```
existing_pseudo = …
```

QTY-2681: Fix query to match instructures

---

app/models/enrollment.rb

[QTY-2879](https://strongmind.atlassian.net/browse/QTY-2879)
During this [outage](https://flipswitch.slack.com/archives/C056MPTAJ7J), it was found that specific enrollments were missing enrollment states. For whatever reason they were either destroyed or never created, preventing the users settings page from loading correctly
when the enrollment state is invoked off the model, we now create the enrollment_state if it doesn't exist for the current enrollment.
You can destroy an EnrollmentState tied to existing enrollment and see that it'll get recreated.
N/A
[QTY-2879]: https://strongmind.atlassian.net/browse/QTY-2879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QTY-2879: create enrollment_state if missing

---

lib/messageable_user/calculator.rb
package.json
yarn.lock

[PLT-6458](https://strongmind.atlassian.net/browse/PLT-6458)
As a result of the NIM new non-primary teacher roles being created in Canvas, these roles should not be options to be sent messages to from students under the 'teachers' group. For example, a teacher with a Learning Success Partner role should not populate under the 'teachers' group when a student sends a message.
Modify the existing SQL logic which shows students the existing 'teachers' and 'teaching assistant' groups only. The modification made enforces that the only teachers that show up under the 'teachers' group have a type and role of 'TeacherEnrollment' only.
- Tested locally and on newidsandbox by: 
- creating multiple users across a variety of roles (student, primary teacher, non-primary teacher, etc.)
- Drafting up a …

(B) PLT-6458: Disable student messages to new NIM non-primary teacher roles

---

lib/messageable_user/calculator.rb

[PLT-6458](https://strongmind.atlassian.net/browse/PLT-6458)
In reference to this [bug](https://strongmind-4j.sentry.io/issues/4321995983/?project=6262567), adding this option will facilitate more granular control over messaging constraints for enrollment types. This removes unintended behavior by leaving default messaging scopes alone.
Create the attribute within the options and apply the conditional logic to our query to dictate whether or not to include it in the enrollment scope. 
- Ensured that our previous changes are continuing to work as expected. 
- Verified that group messaging continues to work as expected.
[PLT-6458]: https://strongmind.atlassian.net/browse/PLT-6458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLT-6458: Create option for primary teacher filtering on messages

---

app/controllers/conversations_controller.rb

add_message
[QTY-1249](https://strongmind.atlassian.net/browse/QTY-1249)
if the add_message endpoint is hit without a body, the code will try and return a :bad_request....which happened to be misspelled. this pr fixes the typo.
n/a
once this is deployed to newidsandbox, we can attempt to hit this enpoint with no body. we should expect a 400.
n/a
[QTY-1249]: https://strongmind.atlassian.net/browse/QTY-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-1249: fix typo, return :bad_request vs :bad_reqquest in

---

app/controllers/lti_api_controller.rb
lib/canvas/errors/info.rb

[QTY-377](https://strongmind.atlassian.net/browse/QTY-377)
Currently, when grade_passback fails, we only get info about the tool ID and domain. BY adding more logging, we're hoping to get more info about the assignment/course that is failing grade passback
Log more info about the request body that comes in on grade passback. Try `Sentry.Capture` in addition to the existing `Canvas::Errors.capture` to see if we get more info.
Make sure app is up and running locally (since we just added logging, there should be no breaking changes)
N/A
[QTY-377]: https://strongmind.atlassian.net/browse/QTY-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QTY-377 add more logging for grade_passback failures

---

public/javascripts/context_modules.js

[QTY-4252](https://strongmind.atlassian.net/browse/QTY-4252)
When a user creates a new module item, they should be able to click and view the item. Without this change, user will see a "page not found" error if they try to view the item right after creating it unless they refresh. With our change, page will load without the need to refresh.
The method `addItemToModule()` is called in several places. For new module items, this gets called twice. The first time it is called, the module item looks like this:
The second time, the item looks like this:
The module item id gets set using data.id. We added a fallback value of `data["item[id]"]` to handle the case that the module comes through as the structure in the first image.
This gives us a valid URL to navigate to when the user clicks on the …

QTY-4252 ensure module item id is set for new module items

---

package.json
yarn.lock

Reverts StrongMind/canvas-lms#527
canvas can't handle large bumps in dependencies like this.

Revert "Bump tinymce from 4.5.7 to 5.10.8"

---

client_apps/canvas_quizzes/package.json
client_apps/canvas_quizzes/yarn.lock

Reverts StrongMind/canvas-lms#530

Revert "Bump lodash from 2.4.1 to 4.17.21 in /client_apps/canvas_quizzes"

---

app/controllers/lti_api_controller.rb
lib/basic_lti/basic_outcomes.rb

[QTY-377](https://strongmind.atlassian.net/browse/QTY-377)
up until now, we've been returning 200s on grade_passback calls whether they were successful or not. this pr changes the behavior to now return a 422 if unprocessable. 
attempt to process the payload for grade passback, if success return 200. otherwise return 422 and include the reason for the failure
deployed to newidsandbox
* run through a course using pointful cartridge, you can see grades get updated as you progress through the content
* postman - posted both a good payload & a bad payload
n/a
[QTY-377]: https://strongmind.atlassian.net/browse/QTY-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-377: update grade_passback to return 422 in cases where we can't process the payload

---

app/models/course.rb
config/initializers/periodic_jobs.rb
lib/grade_calculator.rb

[QTY-5203](https://strongmind.atlassian.net/browse/QTY-5203)
this change has the grade calculator store up each course it needs to touch in a redis SET. once an hour our new job will process the set and touch any courses that need to be touched.
remove the course.touch, replace with a write to a redis SET, adding the course id.
once an hour a new job will run to process the SET, touching each course.
rspec, will test manally when image is created
n/a
[QTY-5203]: https://strongmind.atlassian.net/browse/QTY-5203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

QTY-5203: reduce the amount of course touching to once an hour

---

config/initializers/sentry.rb

We are still blowing through our 100k transactions for the org in less than a day. Would like to try this out in Central, so we need to turn it off here.
Set sample rate to 0.
https://docs.sentry.io/platforms/ruby/performance/

Turn off sentry tracing for now

---

app/controllers/application_controller.rb
app/views/layouts/application.html.erb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/HWTJ-2)
So that a student can access AI help in a course, expose an AI Assistant widget, behind a feature flag
Use a launch darkly application helper method.
Will test either with qwerty help, or in test env.

Add AI Assistant widget, behind a feature flag.

---

app/controllers/application_controller.rb
app/controllers/student_assignment_settings_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6483)
prevent students from posting to the max_attempts endpoint in order to add an additional attempt
reject with a 401 if user isn't doesn't have a role with `manage_assignments` permissions
deployed to newidsandbox, we were able to reproduce the vulnerability before our change and after the change. after change user gets a 401 when done as student.
before
after

QTY-6483 speed grader vulnerability

---

app/models/account.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/STK-7127)
When troubleshooting role issues, we encountered this case where an inactive role is retrieved by this code, rather than the active one that replaced it.
Order by workflow_state so we get the active one.
Ran this in console. See screenshot below.

STK-7127 Add order by workflow_state in role_scope

---

app/models/context_module.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6810)
related to [sentry issue](https://strongmind-4j.sentry.io/issues/4042470242/events/394096a518b649bd9e15e12333b8cfdc/?project=6262567)
in rare cases, it looks like this endpoint is hit without a user....which causes issues once we drop down into the model code.
exit function early if user is nil
n/a
n/a

QTY-6810: fix NoMethodError for available_for?

---

app/controllers/wiki_pages_api_controller.rb

[QTY-6270](https://strongmind.atlassian.net/browse/QTY-6270)
In cases where there were no revisions current_version was throwing an error, instead we should handle it as a nil
if current_version fails due to a NoMethodError, current_version is nil
Managed to reproduce error on new-id-sandbox will confirm the fix worked when we are able to deploy to new-id-sandbox
[QTY-6270]: https://strongmind.atlassian.net/browse/QTY-6270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-6270: Set current version to nil if NoMethodError

---

app/controllers/wiki_pages_api_controller.rb

[QTY-6270](https://strongmind.atlassian.net/browse/QTY-6270)
Purpose
Check if a page has versions otherwise throw 404 error when a revision is trying to be accessed
Approach
Use proper error handling
Testing
Managed to reproduce error on new-id-sandbox will confirm the fix worked when we are able to deploy to new-id-sandbox
[QTY-6270]: https://strongmind.atlassian.net/browse/QTY-6270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-6270: Use proper error handling when a page has no revisions

---

app/models/quizzes/quiz_submission.rb
lib/api/html/content.rb

[QTY-4526](https://strongmind.atlassian.net/browse/QTY-4526)
Sanitize styles that can cover up the applications screen blocking users from using the app
Sanitize styles using regex
Local testing on canvas VM
https://github.com/StrongMind/canvas-lms/assets/121902867/757f9b2e-266a-45ca-a9dc-b2d77c0bca06
[QTY-4526]: https://strongmind.atlassian.net/browse/QTY-4526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-4756: Sanitize html styles on quiz and discussion questions

---

app/models/stream_item.rb
config/initializers/active_record.rb

[QTY-4245](https://strongmind.atlassian.net/browse/QTY-4245)
Fixing a unique constraint issue
Related comment `config/initializers/active_record.rb#unique_constraint_retry` (line 577):
Due to race conditions it seems they attempted to use retires, however they were only retrying once without any pause between retries
Increase retry count and wait slightly between retries to give race conditions more breathing room to finish
Will need to wait and see if this bug resurfaces
[QTY-4245]: https://strongmind.atlassian.net/browse/QTY-4245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-4245: Unique violation

---

app/controllers/context_modules_controller.rb

[QTY-7031](https://strongmind.atlassian.net/browse/QTY-7031)
`@tag` will only be nil if no item is found in the `@module.add_item` method
Throw a 404 if tag is nil
Tested on the canvas vm via teamviewer

(B) QTY-7031: Properly capture a 404 error

---

app/models/discussion_entry.rb

[QTY-6900](https://strongmind.atlassian.net/browse/QTY-6900)
to fix sentry [issue](https://strongmind-4j.sentry.io/issues/3466494521/events/70a4e211e48e4c2fae8857a9197ff08a/?project=6262567&referrer=next-event) undefined method `workflow_state=' for nil:NilClass
check for nils before trying to update submission records
manually tested. Made sure there were no errors in Chrome dev console in the network tab and no errors in the server logs
[QTY-6900]: https://strongmind.atlassian.net/browse/QTY-6900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-6900: check for submission nils before attempting to update them

---

app/coffeescripts/views/conversations/MessageFormDialog.coffee

[QTY-6486](https://strongmind.atlassian.net/browse/QTY-6486)
To fix sentry [issue](https://strongmind-4j.sentry.io/issues/4978116410/?project=6262567&referrer=jira_integration) Validation failed: Body is too long (maximum is 65,535 characters)
add validation to coffeescript file that checks the length of the body on form submit
manually tested by trying to submit a form above the character limit. 
[QTY-6486]: https://strongmind.atlassian.net/browse/QTY-6486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-6486: add character validation to conversation body

---

app/models/importers/assessment_question_importer.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/KAPE-3301)
When importing QTIs built from learnosity's conversion tool, Canvas sets the bank title to "No Name - [course name]" if there is more than one item in the QTI file.
Only set the bank title to the title in the hash (that comes from inside certain types of QTI exported files) if it exists.
RSpec, local testing
Before
After

KAPE-3301 Stop clobbering bank titles when there is more than one question

---

config/routes.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6895)
remove root `/users` path as it's not fully implemented and causes exceptions, instead we now get a 404.
remove the root resource, but keep the namespace.
deployed to new-id-sandbox,  
* verified max attempts still works with this route
* `/users/:user_id/assignments/:assignment_id/settings/max_attempts"` 
n/a

QTY-6895: remove un-implemented routes to stop exceptions

---

app/models/quizzes/quiz_statistics/item_analysis/summary.rb

[QTY-7404](https://strongmind.atlassian.net/browse/QTY-7404)
Solve ArgumentError comparison of NilClass with 3.0 failed 
Compact the dictionary to remove nil values
Rails console to reproduce error and then fix it
[QTY-7404]: https://strongmind.atlassian.net/browse/QTY-7404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-7404:  Compact dictionary with nil values

---

lib/canvas/core_ext/oauth2.rb

[QTY-6800](https://strongmind.atlassian.net/browse/QTY-6800)
Gather more information around the failure
Add Rails logging
None
[QTY-6800]: https://strongmind.atlassian.net/browse/QTY-6800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-6800: Add logging for OAuth error

---

lib/dates_overridable.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6231)
in response to this [sentry bug](https://strongmind-4j.sentry.io/issues/4916400007/?project=6262567&referrer=jira_integration). when the assignment is created, an email is trying to be sent out with info about the assignment, the problem is the assignment has no due date. the code is raising an exception on `all_due_dates.first[:due_at]`
update `teacher_due_date_for_display` to return nil in the case we hit `all_due_dates`  and the assignment has no due date.
n/a
n/a

(B) QTY-6231: update teacher_due_date_for_display to return nil for all_due_dates if hash is empty

---

app/controllers/files_controller.rb

[QTY-7601](https://strongmind.atlassian.net/browse/QTY-7601)
to fix bug from [this](https://strongmind-4j.sentry.io/issues/3376162941/events/b96728761454453d925467de333a4222/?project=6262567&referrer=next-event) sentry issue
manually handle error if the context is nil due to no context code, which would be derived from a user id.
manually tested in local env
[QTY-7601]: https://strongmind.atlassian.net/browse/QTY-7601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-7601: return error when user is undefined when uploading avatar

---

app/controllers/application_controller.rb

[QTY-5077](https://strongmind.atlassian.net/browse/QTY-5077)
Users get unhelpful errors when attempting to navigate to unsupported module items, these are then raised as sentry errors.
Replace the existing raise with a logger, allowing users to see a more helpful error and creating logs of the event without raising to sentry.
Recreated the event by navigating to a module item from a course, while triggering the else statement that shows the exception handling.
[QTY-5077]: https://strongmind.atlassian.net/browse/QTY-5077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-5077: Log Error instead of Raising When Navigating to Unsupported Module Items

---

app/controllers/external_tools_controller.rb
app/models/context_external_tool.rb

[QTY-7635](https://strongmind.atlassian.net/browse/QTY-7635)
Catch and throw a bad request error instead of erroring out
Begin rescue an InvalidURI error
Tested on newidsandbox to reproduce the error, was not able to reproduce locally.. so will test again on newidsandbox to see if the issue is resolved
[QTY-7635]: https://strongmind.atlassian.net/browse/QTY-7635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-7635: Catch invalid uri error and return a bad request

---

app/controllers/users_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6867)
To fix [this](https://strongmind-4j.sentry.io/issues/3376253541/?project=6262567&referrer=jira_integration) Sentry issue that was caused by a users email being updated to an empty string
only assign a new email to the user if the email is present
manually tested in view in a local env
n/a

(B) QTY-7939: only assign email if email string is not empty

---

app/controllers/users_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6867)
to fix [this](https://strongmind-4j.sentry.io/issues/3376253541/?project=6262567&referrer=jira_integration) sentry issue which was caused when a user's email was updated to be an empty string
change controller to only update the users email if the new_email param is not empty
manually tested in a local env
n/a

(B) QTY-6867: only assign email if email string is not empty

---

app/controllers/login/oauth2_controller.rb
lib/canvas/core_ext/oauth2.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/TEAM-NUMBER)
Stop rails from blowing up on the backend and give back an error to the client
Return unauthorized request
To test OAuth2 I need to test in an identity environment, so I will test in newidsandbox first.

(B) QTY-7957: Return a 401 when getting token fails

---

gems/turnitin_api/lib/turnitin_api/outcomes_response_transformer.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-7536)
[Here](https://strongmind.atlassian.net/browse/QTY-7536) is the link for the bug in Jira.
This is happening when we try to access properties on a non-existent key in the response body. Our guard clause is ultimately what is throwing this exception:
```rb
submission.submitted_at = turnitin_client.uploaded_at if turnitin_client.uploaded_at
```
Here uploaded_at is throwing the issue with the following code because meta is not present in this case:
```rb
response.body['meta']['date_uploaded']
```
I have created a method to always return nil in these cases in order for these methods to behave as expected.
* Tried to write and run tests for this but it's like, impossible.

(B) QTY-7536: Safely access the response body

---

app/coffeescripts/models/Assignment.coffee
app/models/assignment.rb
app/views/jst/assignments/AssignmentListItem.handlebars
lib/api/v1/assignment.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-8126)
to fix an outage where a url would not have the context_module_id param which would cause issues when a student was doing a pre test
add context tag id to the assignment json paylaod so that it is available in the handlebar view so that the correct link could be built
manually tested in a local env

(B) QTY-8126: add context_module_id to assignment json

---

app/views/layouts/application.html.erb

pendo, otherwise default to original behavior.
[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-8507)
the pr introduces the idea of using the users integration id from pseudonym when initializing pendo, if the user doesn't have a pseudonym with an integration id....then we'll default to the original behavior
update the application.html.erb to use the users integration id if it exisits, otherwise use the original value.
testing on newidsanbox
n/a

(B) QTY-8507: use users integration id off pseudonym if present for

---

app/views/layouts/application.html.erb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-8507)
this PR resolves the issue where `@current_user` may not be set.
add a check for `@current_user`
will check for integrations ids as users ids in pendo from enterprise canvas.
n/a

(B) QTY-8507: update pendo user id to be users integration id | other original behaviour

---

app/controllers/courses_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-9035)
Course updates were causing course conclude dates to changes dates depending on their timezone.
Change behaviour of timezone changing updates to only fire on course creation and course update from the UI.
Create specs in the shim

QTY-9035: Adjust timezone when updating course from newidsandbox

---

Gemfile.d/app.rb
config/initializers/delayed_job.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-3136)
We intend to dynamically scale numbers of workers in order to both more quickly handle spikes in our queues and also to save money when we do not have outstanding jobs.  This will publish the metrics needed for this work.
Use the hooks in the inst-job initializer to publish queue age information to cloudwatch metrics.
Tested in canvas-stage.
We also verified that the IAM users that run canvas have access to write to cloudwatch metrics.

BEL-3136 Publish queue age metrics

---

app/controllers/application_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6895)
https://strongmind-4j.sentry.io/issues/3479720512/?project=6262567&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=3d&stream_index=3
render unauth if object passed into authorized action is nil so that we don't blow up when trying to determine if the
user is attempting to make an authorized action
add guard clause

QTY-6895 Prevent blowup when trying to determine #authorized_action

---

app/controllers/lti_api_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-13600)
To troubleshoot why POES takes 10 seconds on average to do this, we are hoping we can see some pattern in the types of students/courses that take 20-60+ seconds in POES
Use puts to log JSON so that cloudwatch can parse it easier.

PLT-13600: Add logging for grade passback call

---

app/controllers/content_exports_controller.rb

[QTY-8981](https://strongmind.atlassian.net/browse/QTY-8981)
In some cases context was nil when getting to this line
If context is nil assume user is unauthorized
[QTY-8981]: https://strongmind.atlassian.net/browse/QTY-8981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-8981: Return unauthorized if context is nil

---

app/controllers/users_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-7191)
we don't need to be raising exceptions when a user create is posted for a user who already exists for a specific identity id
catch the `index_pseudonyms_on_unique_id_and_account_id` and return a 409
n/a
n/a

QTY-7191: return 409 on conflicts for  user creation with an existing integration id exists for a specific user

---

app/models/assignment.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-13623)
None of our schools have grading periods. Running this preload is wasteful. Noticed when going over all our queries to try to improve performance.
Turn off preload of grading periods whenever we query for the submissions on an assignment.

PLT-13623 Remove extra query

---

app/views/jst/courses/roster/rosterUser.handlebars

[Link to Jira ticket](https://strongmind.atlassian.net/browse/KAPE-5194)
Hide Custom Placement in UI
Add "display: none" to list item element
WIP - I'm trying to figure out how to run specs
Before:
After:

KAPE-5194: Hide old custom placement button

---

app/models/enrollment/recent_activity.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-6959)
We are addressing occasional deadlocks when calling `update_all` on student
enrollments.
When we try to update the `last_activity_at` on enrollments, sometimes
we have two and one has `deleted` activity_state. This is causing a
deadlock with transactions that look something like this:
```rb
UPDATE "public"."enrollments"
SET "total_activity_time" = 26978,
"last_activity_at"   = '2024-11-15 17:19:59.273329'
WHERE "enrollments"."course_id" = 33484
AND "enrollments"."user_id" = 240618; /*controller:submissions_api,action:for_students,hostname:75a8ffb08c13,pid:25784,context_id:5bef41bb-6174-4b00-80a7-0e03a652d607,line:/config/initializers/active_record.rb:960:in `update_all'*/
UPDATE "public"."enrollments"
SET …
```

QTY-6959: Try addressing long-standing deadlocks

---

config/initializers/sentry.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/TEAM-NUMBER)
We're experiencing issues with grade passback due to poes being under extreme pressure making ~600 queries a second on other tasks. Add a low sample rate for canvas as a whole, so we can work out which transaction is causing this.
Increase default sample rate to 0.0001

PLT-14101 Increase sample rate to always be 1 in 10000 for transactions other than grade passback

---

app/controllers/login/oauth2_controller.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-8152)
So that the rescue does not throw a `NameError` due to not recognizing `Oauth2::Error`
The underlying error being thrown should be `OAuth2::Error` with a capital "A".
The rescue that is now throwing the `NameError` was introduced ~6 months ago https://github.com/StrongMind/canvas-lms/commit/0209c2d16eeb274b36615397241de27e59cb3d43
Update constant in rescue block
N/A
Underlying error:

(B) QTY-8152: Change "Oauth2::Error" to OAuth2::Error with a capital "A"

---

app/coffeescripts/views/conferences/EditConferenceView.coffee

[QTY-10234](https://strongmind.atlassian.net/browse/QTY-10234)
There is a visual bug when a user updates a conference for a course
Update state after the update is successful
Will be testing on new-id-sandbox
[QTY-10234]: https://strongmind.atlassian.net/browse/QTY-10234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-10234: Fix visual bug for conference updates

---

app/coffeescripts/views/conferences/EditConferenceView.coffee

[QTY-10234](https://strongmind.atlassian.net/browse/QTY-10234)
Force a refresh, I timeboxed other solutions to manually update the local state.. settled on brute forcing the issue and forced a form reset on update.
Resubmit the form if updating as the creation flow does not seem to have the original issue
Tested on the canvas vm via team viewer
[QTY-10234]: https://strongmind.atlassian.net/browse/QTY-10234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(B) QTY-10234: Force the conference form to refresh with a submit

---

.github/workflows/notify_canvas_docker.yml

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-11338)
Address the action run failure, `curl: (22) The requested URL returned error: 401`
This pull request includes a change to the `.github/workflows/notify_canvas_docker.yml` file. The change updates the environment variable used for the GitHub REST API call.
* [`.github/workflows/notify_canvas_docker.yml`](diffhunk://#diff-9517137574fa4a237484d22245054f6dbc793a423c188facd9afa8db63577f61L24-R24): Changed the environment variable `CI_TOKEN` to use `secrets.DEVOPS_GH_TOKEN` instead of `secrets.CI_TOKEN`.
merge run and verify

QTY-11338 Update the gh token b/c the old one is probably expired

---

config/initializers/sentry.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-13623)
We still need more data on why this call is sometimes so slow.
Use rack_env - not sure the transaction context name is working. But I tested the query string and it is working.

PLT-13623: Try increasing sampling rate for grade passback again

---

Gemfile.d/app.rb
config/initializers/rack_timeout.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4804)
We are missing traces for transactions that are running slowly, attempt to fix this.
Add rack-timeout so that when transactions time out, they end up as exceptions in sentry, so that we can see what was running when it failed.
We will necessarily have to test this in our dev environment.

(B) BEL-4804 Enable more diagnosis tools for grade passback 504s

---

app/controllers/application_controller.rb
config/initializers/rack_timeout.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4804)
Capture more information for slow transactions that we do not wish to timeout.
Dealing with the last of these grade_passback errors, we're not getting Rack Timeouts for some of them. This will produce a different exception and send it to sentry, but not kill the transaction.
Checked that the change works in a local central instance. Will need to double check on CDCR or new-id-sandbox.

BEL-4804 Send errors for slow transactions

---

config/initializers/rack_timeout.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4804)
Reduce the initial number of slow transaction exceptions into sentry.
Change the timeout to 30 seconds.

BEL-4804 Change time warning to 30 seconds.

---

app/controllers/application_controller.rb
config/initializers/rack_timeout.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-4804)
Solve bug with stack trace showing the main thread in sentry, preventing us from gaining more telemetry to work out slow requests (in particular for grade passback, but elsewhere also).
We originally tested the 30 second soft timeout sentry errors with central, as we had no easy way to test them with canvas. Turns out that Canvas removes the ActionDispatch request id middleware, which we were dependent upon.
Use the rack timeout requestdetails id instead to grab the correct thread.
Tested in dev and ensured the backtrace reached the logger.

BEL-4804 Solve bug with stack trace

---

app/views/jst/announcements/IndexView.handlebars

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-11777)
Sometimes the 'add announcement' button is missing from the page.
There was a condition where if there was expired announcements and no active announcements, the 'add announcement' button would not render. Added logic to render the button in this condition if the user has the correct permissions. 
Plan to recreate the issue in New-Id-Sandbox and verify this fixes the issue.
Current issue, where the 'add announcement' button is missing:

QTY-11777: Add missing announcement button

---

config/initializers/rack_timeout.rb
config/initializers/sentry.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-13818)
* Update Sentry to be less noisy for Canvas-lms
* Allow the threshold for reporting slow queries to be adjustable via an ENV variable
* Make Rack Timeout Exception throw after 55 seconds (bumped up from 50 seconds)
* Report slow queries when they take 50 seconds instead of 30 seconds
* Determine slow queries from an ENV variable if it exists, otherwise default to 50 seconds
* Have Sentry ignore Rack Timeouts, since we will report them via SlowQuery errors already.

QTY-13818: Update Slow Transaction Sentry Behavior

---

app/controllers/assignment_groups_controller.rb
app/models/assignment.rb
lib/api/v1/assignment_group.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-14666)
Without preloading, when the code iterates through each assignment and calls context_tag_id, it triggers a separate database query for each assignment to fetch its associated context module tags. This is a classic N+1 query problem:
- One query to fetch all assignments
- N additional queries (one per assignment) to fetch each assignment's context module tags
For courses with many assignments, this can lead to hundreds of individual database queries, causing significant performance degradation.
The preloading approach solves this by:
- Loading all assignments in a single query
- Loading all related context module tags for all assignments in a single additional query
- Associating the loaded tags with their respective …

(B) QTY-14666: Preload context module tags

---

lib/authentication_methods.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/BEL-5313)
We're currently silently failing when we fail to talk to the attendance service.  This was originally done because the maintainers of the codebase were not using sentry, and it is important for the service to remain up (fail open) when attendance is down.
Use the canvas errors capture service to send errors to sentry.
Will test in stage before sending to prod.

(B) BEL-5313: Add Sentry error reporting for attendance service

---

public/401.html
public/404.html

[Link to Jira ticket](https://strongmind.atlassian.net/browse/QTY-15239)
Standardize error HTML pages
Add 401, 404, and replace 500 html pages with central's error pages
Go to the <url>/401, <url>/404, <url>/500 to verify

(S) QTY-15239: Replace 401, 404, 500 html pages with central's

---

config/initializers/rack_timeout.rb

[Link to Jira ticket](https://strongmind.atlassian.net/browse/PLT-16913)
Stop the spamming of Sentry on items that are not currently a priority.
Increase the threshold from 50 to 90 seconds. Also, removed the variable and hard set the value.
N/A
N/A

PLT-16913 Update slow query check

---

app/models/enrollment.rb

[QTY-17506](https://strongmind.atlassian.net/browse/QTY-17506)
Fix PostgreSQL deadlock errors occurring when multiple enrollment conclusions are processed concurrently for the same user. The deadlock happens when two processes attempt to update the same user record (via user.touch) in different transaction orders, creating a circular wait condition that causes one transaction to fail with PG::TRDeadlockDetected.
Wrap the enrollment conclusion logic in a database transaction with explicit row-level locking on the user record using with_lock. This ensures that when multiple enrollments for the same user are being concluded simultaneously, they will be processed sequentially rather than concurrently, eliminating the deadlock condition.
Changes made:
Added User.transaction block around the …

Add advisory locking around user updates
